#ifndef __CONFIG_ROM_H__
#define __CONFIG_ROM_H__

#include "iomap.h"

/*
 * System CONFIGS
 */

#define CONFIG_TIMER_FREQ		95000000	/* 95M Hz */
#define CONFIG_COUNTER_FREQ		20000000	/* 20M  Hz Timer */

/*use arch timer*/
#define	 TICKS_PER_US			(20)
#define  TICKS_PER_MS			(20000)
#define	 TICKS_PER_S			(20000000)

#define  ARCH_TIMER_TICKS_PER_MS    TICKS_PER_MS
#define	 CONFIG_APB_CLOCK		(95000000)
#define	 CONFIG_SERIAL_BAUDRATE		(115200)

#define	 CONFIG_BAUDRATE_115200		(115200)
#define	 CONFIG_BAUDRATE_921600		(921600)
/*
 * Memory CONFIGS
 */
#define CONFIG_ROM_START		ROM_BASE	
#define CONFIG_ROM_SIZE			0x00010000	/* 64k */

#define CONFIG_SRAM_START	        IRAM_BASE	
#define CONFIG_SRAM_SIZE		0x00200000	/* 2M */

#define CONFIG_BB_MEM_START        0x00500000	
#define CONFIG_BB_MEM_SIZE		0x00400000	/* 4MB */

#define CONFIG_DRAM_START               _DDR_BASE 
#define CONFIG_DRAM_SIZE                0x40000000

#define CONFIG_BOOT_RSVADDR_SIZE    (8 * 1024)
#define CONFIG_BOOT_RSVADDR_START  (CONFIG_SRAM_START + CONFIG_SRAM_SIZE -CONFIG_BOOT_RSVADDR_SIZE)

#define CONFIG_ROM_RUN_RANGE        (0x00080000) /* 512k */
#define CONFIG_ROM_RSVADDR          (CONFIG_SRAM_START + CONFIG_ROM_RUN_RANGE - CONFIG_BOOT_RSVADDR_SIZE)
/*
 * SP/PageTable CONFIGS
 */

#define CONFIG_PGTABLE_SIZE		(16*1024)
#define UNUSE_ADDR             (8*1024)
/*for internal sram*/
#define	CONFIG_TTB_BASE		   (CONFIG_BOOT_RSVADDR_START - CONFIG_PGTABLE_SIZE - UNUSE_ADDR)

#define CONFIG_SYS_INIT_SP_ADDR    (CONFIG_TTB_BASE)

#define CONFIG_STACKSIZE_SVC       (8*1024)    /* regular stack */
#define CONFIG_STACKSIZE_IRQ       (4*1024)    /* IRQ stack */
#define CONFIG_IRQ_STACK_START     (CONFIG_SYS_INIT_SP_ADDR - CONFIG_STACKSIZE_SVC)
#define CONFIG_EXCEPTION_STACK_START    (CONFIG_IRQ_STACK_START - CONFIG_STACKSIZE_IRQ)

#define	CONFIG_SP_MAX_SIZE	   (CONFIG_STACKSIZE_SVC + CONFIG_STACKSIZE_IRQ)
#define CONFIG_SYS_MALLOC_LEN      (CONFIG_MALLOC_LEN_KB * 1024) /* malloc() len */
#define	CONFIG_SYS_MALLOC_START	   (CONFIG_SYS_INIT_SP_ADDR - CONFIG_SYS_MALLOC_LEN - CONFIG_SP_MAX_SIZE)

//#define CONFIG_SRAM_BL_START        (0x290000)
#define CONFIG_SRAM_BL_SIZE     (CONFIG_SRAM_START + CONFIG_SRAM_SIZE - CONFIG_SRAM_BL_START - CONFIG_BOOT_RSVADDR_SIZE - UNUSE_ADDR)

#define CONFIG_SYS_PBSIZE 1024

#if ((CONFIG_TTB_BASE & 0x3fff) > 0)
#error ttb base align 14bit
#endif

#endif // __CONFIG_ROM_H__
