#ifndef IRQ_DEFS__H__
#define	IRQ_DEFS__H__

typedef enum
{
    SYS_IRQ_ID_TIMER0                      = 0,
    SYS_IRQ_ID_TIMER1                      = 1,
    SYS_IRQ_ID_TIMER2                      = 2,
    SYS_IRQ_ID_TIMER3                      = 3,

    SYS_IRQ_ID_UART0                       = 4,
    SYS_IRQ_ID_UART1                       = 5,
    SYS_IRQ_ID_UART2                       = 6,
    SYS_IRQ_ID_UART3                       = 7,
    SYS_IRQ_ID_UART4                       = 8,
    SYS_IRQ_ID_UART5                       = 9,
    SYS_IRQ_ID_UART6                       = 10,
    SYS_IRQ_ID_UART7                       = 11,

    SYS_IRQ_ID_SPI0                        = 12,
    SYS_IRQ_ID_SPI1                        = 13,
    SYS_IRQ_ID_SPI2                        = 14,
    SYS_IRQ_ID_SPI3                        = 15,

    SYS_IRQ_ID_I2C0                        = 16,
    SYS_IRQ_ID_I2C1                        = 17,
 
    SYS_IRQ_ID_SIM0                        = 18,
    SYS_IRQ_ID_SIM1                        = 19,
    SYS_IRQ_ID_SIM2                        = 20,

    SYS_IRQ_ID_GPIO0                      = 21,
    SYS_IRQ_ID_GPIO1                      = 22,
    SYS_IRQ_ID_GPIO2                      = 23,
    SYS_IRQ_ID_GPIO3                      = 24,
    SYS_IRQ_ID_GPIO4                      = 25,
    SYS_IRQ_ID_GPIO5                      = 26,
    SYS_IRQ_ID_GPIO6                      = 27,
    SYS_IRQ_ID_GPIO7                      = 28,
    SYS_IRQ_ID_GPIO8                      = 29,
    SYS_IRQ_ID_GPIO9                      = 30,
    SYS_IRQ_ID_GPIO10                     = 31,
    SYS_IRQ_ID_GPIO11                     = 32,
    SYS_IRQ_ID_GPIO12                     = 33,
    SYS_IRQ_ID_GPIO13                     = 34,
    SYS_IRQ_ID_GPIO14                     = 35,
    SYS_IRQ_ID_GPIO15                     = 36,
    SYS_IRQ_ID_GPIO16                     = 37,
    SYS_IRQ_ID_GPIO17                     = 38,
    SYS_IRQ_ID_GPIO18                     = 39,
    SYS_IRQ_ID_GPIO19                     = 40,
    SYS_IRQ_ID_GPIO20                     = 41,
    SYS_IRQ_ID_GPIO21                     = 42,
    SYS_IRQ_ID_GPIO22                     = 43,
    SYS_IRQ_ID_GPIO23                     = 44,
    SYS_IRQ_ID_GPIO24                     = 45,
    SYS_IRQ_ID_GPIO25                     = 46,
    SYS_IRQ_ID_GPIO26                     = 47,
    SYS_IRQ_ID_GPIO27                     = 48,
    SYS_IRQ_ID_GPIO28                     = 49,
    SYS_IRQ_ID_GPIO29                     = 50,
    SYS_IRQ_ID_GPIO30                     = 51,
    SYS_IRQ_ID_GPIO31                     = 52,

    SYS_IRQ_ID_SD                     	   = 53,
    SYS_IRQ_ID_QSPI                    	   = 54,
    SYS_IRQ_ID_WDT0                    	   = 55,
    SYS_IRQ_ID_WDT1                    	   = 56,
    SYS_IRQ_ID_DMAC0                   	   = 57,
    SYS_IRQ_ID_DMAC1                   	   = 58,

    SYS_IRQ_ID_SGI0			   = 59,
    SYS_IRQ_ID_SGI1			   = 60,
    SYS_IRQ_ID_SGI2			   = 61,
    SYS_IRQ_ID_SGI3			   = 62,
    SYS_IRQ_ID_SGI4			   = 63,
    SYS_IRQ_ID_SGI5			   = 64,
    SYS_IRQ_ID_SGI6			   = 65,
    SYS_IRQ_ID_SGI7			   = 66,
    SYS_IRQ_ID_SGI8			   = 67,
    SYS_IRQ_ID_SGI9			   = 68,
    SYS_IRQ_ID_SGI10			   = 69,
    SYS_IRQ_ID_SGI11			   = 70,
    SYS_IRQ_ID_SGI12			   = 71,
    SYS_IRQ_ID_SGI13			   = 72,
    SYS_IRQ_ID_SGI14			   = 73,
    SYS_IRQ_ID_SGI15			   = 74,
    SYS_IRQ_ID_SGI16			   = 75,
    SYS_IRQ_ID_SGI17			   = 76,
    SYS_IRQ_ID_SGI18			   = 77,
    SYS_IRQ_ID_SGI19			   = 78,
    SYS_IRQ_ID_SGI20			   = 79,
    SYS_IRQ_ID_SGI21			   = 80,
    SYS_IRQ_ID_SGI22			   = 81,
    SYS_IRQ_ID_SGI23			   = 82,
    SYS_IRQ_ID_SGI24			   = 83,
    SYS_IRQ_ID_SGI25			   = 84,
    SYS_IRQ_ID_SGI26			   = 85,
    SYS_IRQ_ID_SGI27			   = 86,
    SYS_IRQ_ID_SGI28			   = 87,
    SYS_IRQ_ID_SGI29			   = 88,
    SYS_IRQ_ID_SGI30			   = 89,
    SYS_IRQ_ID_SGI31			   = 90,
   
    SYS_IRQ_ID_BB0   			   = 91,
    SYS_IRQ_ID_MP_INT    	       = 92,
    SYS_IRQ_ID_VIT	    		   = 93,
    SYS_IRQ_ID_LDPC	    	       = 94,

} SYS_IRQ_ID_T;

#define NB_SYS_IRQ              (160)

#endif
