obj-y += init.o \
         mem.o  \
         memp.o \
         netif.o    \
         pbuf.o \
         raw.o  \
         stats.o    \
         sys.o  \
         tcp.o  \
         tcp_in.o   \
         tcp_out.o  \
         dhcp.o \
         dns.o  \
         udp.o

obj-y += ipv4/
