#ifndef __RESET_HW_20171211_H__
#define __RESET_HW_20171211_H__

void swrst_cpu1_reset(void);
void swrst_ddr_reset(void);
//void swrst_62M_reset(void);
void swrst_rom_reset(void);
void swrst_ram_reset(void);
void swrst_bb_reset(void);
void swrst_mp_reset(void);
void swrst_dmac0_reset(void);
void swrst_dmac1_reset(void);
void swrst_qspi_reset(void);
void swrst_sd_reset(void);
void swrst_uart0_reset(void);
void swrst_uart1_reset(void);
void swrst_uart2_reset(void);
void swrst_uart3_reset(void);
void swrst_uart4_reset(void);
void swrst_uart5_reset(void);
void swrst_uart6_reset(void);
void swrst_uart7_reset(void);
void swrst_i2c0_reset(void);
void swrst_i2c1_reset(void);
void swrst_spi0_reset(void);
void swrst_spi1_reset(void);
void swrst_spi2_reset(void);
void swrst_spi3_reset(void);
void swrst_sim0_reset(void);
void swrst_sim1_reset(void);
void swrst_sim2_reset(void);
void swrst_pwm_reset(void);
void swrst_gpio_reset(void);
void swrst_timer_reset(void);
void swrst_global_reset(void);
void swrst_gic_reset(void);

#endif //__RESET_HW_20171211_H__
