#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# Copyright (c) 2012, NVIDIA CORPORATION.  All rights reserved.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CMD_JFFS2) += flashinfo.o
obj-$(CONFIG_FS_JFFS2) += jffs2/

#obj-y += fs_internal.o
