#ifndef _MONITOR_H_
#define _MONITOR_H_

#include "hg_types.h"

#define MONITOR_HIGH_SPEED_BAUDRATE     (1875000)
#define	MONITOR_SYNC_CODE_0		        (0x1A)
#define	MONITOR_SYNC_CODE_1		        (0xCF)
#define	MONITOR_SYNC_CODE_2		        (0xFC)
#define	MONITOR_SYNC_CODE_3		        (0x1D)
#define MONITOR_HDR_FORMAT_LEN          (8)

typedef struct monitor_manager{
    U32 lock;
	U32 sequence_num;
}MONITOR_MANAGER_ST;

typedef enum {
    MONITOR_INSTURCTION_TYPE_E_SELF_CHECK = 0,
	MONITOR_INSTURCTION_TYPE_E_DECODE_INFO = 1,
	MONITOR_INSTURCTION_TYPE_E_ENCODE_INFO = 2,
	MONITOR_INSTURCTION_TYPE_E_SHUTDOWN_FOREVER = 3,
	MONITOR_INSTURCTION_TYPE_E_SELF_DESTROY = 5,
	MONITOR_INSTURCTION_TYPE_E_GET_INFO = 6,
	MONITOR_INSTURCTION_TYPE_E_ERR  // 
} MONITOR_INSTURCTION_TYPE_E;


#define MONITOR_RECV_DATA_TIMEOUT    (2000)

#define MONITOR_RECV_BUFF_LEN        (256)
#define MONITOR_SEND_BUFF_LEN        (256)



#endif /* _MONITOR_H_ */

